# Generated by Django 3.1.3 on 2020-12-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='flat.city'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='sqtotaldesc',
            field=models.CharField(max_length=100, verbose_name='Площадь с расшифровкой'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='flat.region'),
        ),
    ]
