# Generated by Django 3.1.3 on 2020-11-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isnew', models.BooleanField()),
                ('floor', models.IntegerField()),
                ('floortotal', models.IntegerField()),
                ('sqkitchen', models.IntegerField()),
                ('sqtotal', models.IntegerField()),
                ('sqtotaldesc', models.IntegerField()),
                ('height', models.IntegerField(null=True)),
                ('wctype', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('housetype', models.CharField(max_length=100)),
                ('housetudestrou', models.BooleanField()),
                ('isapartaments', models.BooleanField()),
                ('createdat', models.DateTimeField()),
                ('phone', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.city')),
            ],
        ),
        migrations.CreateModel(
            name='Freeplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lifttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mertoline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.city')),
            ],
        ),
        migrations.CreateModel(
            name='Parkingtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repairtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roomtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saletype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sallertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Windowsview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metroline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.mertoline')),
            ],
        ),
        migrations.CreateModel(
            name='Flatmetro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.flat')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.metro')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='freeplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.freeplan'),
        ),
        migrations.AddField(
            model_name='flat',
            name='lifttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.lifttype'),
        ),
        migrations.AddField(
            model_name='flat',
            name='parkingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.parkingtype'),
        ),
        migrations.AddField(
            model_name='flat',
            name='repairtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.repairtype'),
        ),
        migrations.AddField(
            model_name='flat',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.roomtypes'),
        ),
        migrations.AddField(
            model_name='flat',
            name='saletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.saletype'),
        ),
        migrations.AddField(
            model_name='flat',
            name='sallertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.sallertype'),
        ),
        migrations.AddField(
            model_name='flat',
            name='windowsview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.windowsview'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flat.city')),
            ],
        ),
    ]
