# Generated by Django 3.1.3 on 2020-12-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20201214_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип Санузла (для выборки)',
                'verbose_name_plural': 'Тип Санузла (для выборки)',
            },
        ),
        migrations.AlterField(
            model_name='flat',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='wctype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.wctype', verbose_name='Тип санузла'),
        ),
    ]
