# Generated by Django 3.1.3 on 2020-12-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20201130_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='flat.region'),
        ),
    ]
