# Generated by Django 3.1.3 on 2020-12-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_region_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='flat.city'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floortotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='housetudestrou',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='housetype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='isapartaments',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='lifttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.lifttype'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='parkingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.parkingtype'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='repairtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.repairtype'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='sqkitchen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='wctype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='windowsview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.windowsview'),
        ),
    ]
