# Generated by Django 3.1.3 on 2020-12-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_auto_20201214_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='metro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.metro', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='coord_lat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='coord_long',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='долгота'),
        ),
    ]
