# Generated by Django 3.1.3 on 2021-01-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_auto_20201217_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип Балкон/Лоджия(для выборки)',
                'verbose_name_plural': 'Тип Балкон/Лоджия(для выборки)',
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='balcony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.balcony', verbose_name='Балкон/Лоджия'),
        ),
    ]
