# Generated by Django 3.1.3 on 2021-01-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_auto_20210124_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип Лоджия(для выборки)',
                'verbose_name_plural': 'Тип Лоджия(для выборки)',
            },
        ),
        migrations.AlterModelOptions(
            name='balcony',
            options={'verbose_name': 'Тип Балкон(для выборки)', 'verbose_name_plural': 'Тип Балкон(для выборки)'},
        ),
        migrations.AlterField(
            model_name='flat',
            name='balcony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.balcony', verbose_name='Балкон'),
        ),
        migrations.AddField(
            model_name='flat',
            name='loggia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.loggia', verbose_name='Лоджия'),
        ),
    ]
