# Generated by Django 3.1.3 on 2021-01-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0008_auto_20210124_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floortype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип перекрытий(для выборки)',
                'verbose_name_plural': 'Тип перекрытий(для выборки)',
            },
        ),
        migrations.AlterModelOptions(
            name='balcony',
            options={'verbose_name': 'Тип Балкона(для выборки)', 'verbose_name_plural': 'Тип Балкона(для выборки)'},
        ),
        migrations.AlterModelOptions(
            name='loggia',
            options={'verbose_name': 'Тип Лоджии(для выборки)', 'verbose_name_plural': 'Тип Лоджии(для выборки)'},
        ),
        migrations.AddField(
            model_name='flat',
            name='floortype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.floortype', verbose_name='Тип перекрытий'),
        ),
    ]
