# Generated by Django 3.1.3 on 2021-01-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0009_auto_20210124_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип подъезды(для выборки)',
                'verbose_name_plural': 'Тип подъезды(для выборки)',
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='entrances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.entrances', verbose_name='Подъезды'),
        ),
    ]
