# Generated by Django 3.1.3 on 2021-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0012_auto_20210124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='accidentrate',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аварийность'),
        ),
    ]
