# Generated by Django 3.1.3 on 2021-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0013_flat_accidentrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='garbagechute',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мусоропровод'),
        ),
    ]
