# Generated by Django 3.1.3 on 2021-01-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0015_auto_20210124_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='saletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flat.saletype', verbose_name='Тип продаж'),
        ),
    ]
