# Generated by Django 3.1.3 on 2021-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0016_auto_20210124_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
    ]
