# Generated by Django 3.1.3 on 2021-01-25 18:59

from django.db import migrations, models
import flat.models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0017_auto_20210124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimges',
            name='pik',
            field=models.ImageField(upload_to=flat.models.flat_upload_path),
        ),
    ]
