# Generated by Django 3.1.3 on 2021-01-25 19:14

from django.db import migrations, models
import django.db.models.deletion
import flat.models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0018_auto_20210125_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimges',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='flat.flat'),
        ),
        migrations.AlterField(
            model_name='flatimges',
            name='pik',
            field=models.FileField(upload_to=flat.models.flat_upload_path),
        ),
    ]
